import type {
  Client,
  Order,
  Domain,
  Hosting,
  User,
  GeneratedSite,
  WhatsAppMessage,
  AIAgent,
  DashboardStats,
} from "@/types";

export const mockStats: DashboardStats = {
  total_revenue: 84750,
  monthly_revenue: 12340,
  total_orders: 247,
  total_clients: 89,
  active_hostings: 64,
  pending_domains: 12,
  pending_payments: 8,
  monthly_growth: 18.5,
};

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Tech Solutions Ltda",
    email: "contato@techsolutions.com.br",
    phone: "(11) 99999-0001",
    company: "Tech Solutions Ltda",
    created_at: "2024-01-15",
    total_orders: 12,
    total_spent: 8500,
  },
  {
    id: "2",
    name: "Maria Fernanda Costa",
    email: "maria@mariafernanda.com",
    phone: "(21) 98888-0002",
    company: "Studio MF",
    created_at: "2024-02-20",
    total_orders: 5,
    total_spent: 3200,
  },
  {
    id: "3",
    name: "Restaurante Bom Sabor",
    email: "admin@bomsabor.com.br",
    phone: "(11) 97777-0003",
    company: "Restaurante Bom Sabor",
    created_at: "2024-03-10",
    total_orders: 8,
    total_spent: 5600,
  },
  {
    id: "4",
    name: "Dr. Roberto Alves",
    email: "roberto@clinicaalves.com",
    phone: "(31) 96666-0004",
    company: "Clínica Alves",
    created_at: "2024-04-05",
    total_orders: 3,
    total_spent: 2100,
  },
  {
    id: "5",
    name: "Fashion Store Brasil",
    email: "loja@fashionstore.com.br",
    phone: "(41) 95555-0005",
    company: "Fashion Store Brasil",
    created_at: "2024-04-18",
    total_orders: 15,
    total_spent: 11200,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    client_id: "1",
    client_name: "Tech Solutions Ltda",
    description: "Desenvolvimento de site institucional",
    value: 3500,
    status: "concluido",
    module: "sales",
    created_at: "2025-05-01",
    due_date: "2025-05-15",
  },
  {
    id: "ORD-002",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    description: "Criação de loja virtual",
    value: 2800,
    status: "processando",
    module: "sales",
    created_at: "2025-05-10",
    due_date: "2025-06-01",
  },
  {
    id: "ORD-003",
    client_id: "3",
    client_name: "Restaurante Bom Sabor",
    description: "Site com cardápio digital",
    value: 1900,
    status: "pendente",
    module: "sales",
    created_at: "2025-05-18",
    due_date: "2025-06-10",
  },
  {
    id: "ORD-004",
    client_id: "4",
    client_name: "Dr. Roberto Alves",
    description: "Landing page médica",
    value: 1200,
    status: "concluido",
    module: "sales",
    created_at: "2025-04-20",
    due_date: "2025-05-05",
  },
  {
    id: "ORD-005",
    client_id: "5",
    client_name: "Fashion Store Brasil",
    description: "E-commerce completo",
    value: 5800,
    status: "processando",
    module: "sales",
    created_at: "2025-05-22",
    due_date: "2025-07-01",
  },
];

export const mockWebsiteOrders: Order[] = [
  {
    id: "WEB-001",
    client_id: "1",
    client_name: "Tech Solutions Ltda",
    description: "Manutenção mensal - Plano Pro",
    value: 350,
    status: "concluido",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
  {
    id: "WEB-002",
    client_id: "3",
    client_name: "Restaurante Bom Sabor",
    description: "Manutenção mensal - Plano Básico",
    value: 150,
    status: "pendente",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
  {
    id: "WEB-003",
    client_id: "5",
    client_name: "Fashion Store Brasil",
    description: "Manutenção mensal - Plano Enterprise",
    value: 800,
    status: "concluido",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
];

export const mockDomains: Domain[] = [
  {
    id: "DOM-001",
    domain: "techsolutions.com.br",
    client_id: "1",
    client_name: "Tech Solutions Ltda",
    expiry_date: "2026-01-15",
    status: "ativo",
    auto_renew: true,
    registrar: "Registro.br",
    price_yearly: 45,
  },
  {
    id: "DOM-002",
    domain: "mariafernanda.com",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    expiry_date: "2025-07-20",
    status: "ativo",
    auto_renew: false,
    registrar: "GoDaddy",
    price_yearly: 60,
  },
  {
    id: "DOM-003",
    domain: "bomsabor.com.br",
    client_id: "3",
    client_name: "Restaurante Bom Sabor",
    expiry_date: "2025-06-10",
    status: "pendente",
    auto_renew: true,
    registrar: "Registro.br",
    price_yearly: 45,
  },
  {
    id: "DOM-004",
    domain: "clinicaalves.com",
    client_id: "4",
    client_name: "Dr. Roberto Alves",
    expiry_date: "2025-05-30",
    status: "vencido",
    auto_renew: false,
    registrar: "Namecheap",
    price_yearly: 55,
  },
];

export const mockHostings: Hosting[] = [
  {
    id: "HOST-001",
    plan: "Plano Pro",
    client_id: "1",
    client_name: "Tech Solutions Ltda",
    monthly_value: 120,
    expiry_date: "2025-12-15",
    status: "ativo",
    server: "BR-SERVER-01",
    disk_usage: 4200,
    disk_limit: 10240,
  },
  {
    id: "HOST-002",
    plan: "Plano Básico",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    monthly_value: 45,
    expiry_date: "2025-08-20",
    status: "ativo",
    server: "BR-SERVER-02",
    disk_usage: 1500,
    disk_limit: 5120,
  },
  {
    id: "HOST-003",
    plan: "Plano Enterprise",
    client_id: "5",
    client_name: "Fashion Store Brasil",
    monthly_value: 280,
    expiry_date: "2025-11-18",
    status: "ativo",
    server: "BR-SERVER-01",
    disk_usage: 18000,
    disk_limit: 51200,
  },
  {
    id: "HOST-004",
    plan: "Plano Básico",
    client_id: "3",
    client_name: "Restaurante Bom Sabor",
    monthly_value: 45,
    expiry_date: "2025-06-10",
    status: "suspenso",
    server: "BR-SERVER-02",
    disk_usage: 800,
    disk_limit: 5120,
  },
];

export const mockUsers: User[] = [
  {
    id: "USR-001",
    name: "Douglas Admin",
    email: "admin@agencia.com",
    role: "admin",
    created_at: "2024-01-01",
    active: true,
  },
  {
    id: "USR-002",
    name: "Ana Financeiro",
    email: "ana@agencia.com",
    role: "financeiro",
    created_at: "2024-02-15",
    active: true,
  },
  {
    id: "USR-003",
    name: "Carlos Suporte",
    email: "carlos@agencia.com",
    role: "suporte",
    created_at: "2024-03-01",
    active: true,
  },
  {
    id: "USR-004",
    name: "Julia Vendas",
    email: "julia@agencia.com",
    role: "vendedor",
    created_at: "2024-04-10",
    active: false,
  },
];

export const mockGeneratedSites: GeneratedSite[] = [
  {
    id: "SITE-001",
    client_id: "1",
    client_name: "Tech Solutions Ltda",
    site_name: "Tech Solutions",
    business_type: "Tecnologia",
    domain: "techsolutions.com.br",
    status: "publicado",
    created_at: "2025-01-15",
    url: "https://techsolutions.com.br",
  },
  {
    id: "SITE-002",
    client_id: "3",
    client_name: "Restaurante Bom Sabor",
    site_name: "Bom Sabor",
    business_type: "Restaurante",
    domain: "bomsabor.com.br",
    status: "em_producao",
    created_at: "2025-03-10",
  },
  {
    id: "SITE-003",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    site_name: "Studio MF",
    business_type: "Fotografia",
    domain: "mariafernanda.com",
    status: "publicado",
    created_at: "2025-02-20",
    url: "https://mariafernanda.com",
  },
];

export const mockMessages: WhatsAppMessage[] = [
  {
    id: "MSG-001",
    contact: "Tech Solutions",
    phone: "+5511999990001",
    message: "Olá! Gostaria de saber sobre o vencimento do meu domínio.",
    direction: "inbound",
    timestamp: "2025-05-26T10:30:00",
    status: "read",
    type: "text",
  },
  {
    id: "MSG-002",
    contact: "Tech Solutions",
    phone: "+5511999990001",
    message:
      "Seu domínio techsolutions.com.br vence em 15/01/2026. Deseja renovar?",
    direction: "outbound",
    timestamp: "2025-05-26T10:32:00",
    status: "read",
    type: "template",
  },
  {
    id: "MSG-003",
    contact: "Restaurante Bom Sabor",
    phone: "+5511977770003",
    message: "LEMBRETE: Sua hospedagem vence em 10/06/2025. Renove agora!",
    direction: "outbound",
    timestamp: "2025-05-25T09:00:00",
    status: "delivered",
    type: "billing",
  },
  {
    id: "MSG-004",
    contact: "Maria Fernanda",
    phone: "+5521988880002",
    message: "Oi, o site ficou ótimo! Muito obrigada pelo trabalho.",
    direction: "inbound",
    timestamp: "2025-05-24T16:45:00",
    status: "read",
    type: "text",
  },
];

export const mockAgents: AIAgent[] = [
  {
    id: "AGENT-001",
    name: "Atendimento Inicial",
    prompt:
      "Você é um assistente da agência. Responda perguntas sobre serviços, preços e prazos de forma profissional e amigável.",
    active: true,
    triggers: ["olá", "oi", "bom dia", "boa tarde", "quero contratar"],
    responses: 342,
    created_at: "2024-01-15",
  },
  {
    id: "AGENT-002",
    name: "Cobrança Automática",
    prompt:
      "Envie lembretes de cobrança automáticos para clientes com pagamentos pendentes. Seja gentil mas firme.",
    active: true,
    triggers: ["vencimento próximo", "pagamento pendente"],
    responses: 87,
    created_at: "2024-02-01",
  },
  {
    id: "AGENT-003",
    name: "Suporte Técnico",
    prompt:
      "Ajude clientes com problemas técnicos básicos. Para problemas complexos, escale para o time de suporte humano.",
    active: false,
    triggers: ["problema", "erro", "não funciona", "site fora do ar"],
    responses: 156,
    created_at: "2024-03-10",
  },
];
