import type {
  Client,
  Order,
  Domain,
  Hosting,
  User,
  GeneratedSite,
  WhatsAppMessage,
  AIAgent,
  DashboardStats,
} from "@/types";

export const mockStats: DashboardStats = {
  total_revenue: 84750,
  monthly_revenue: 12340,
  total_orders: 247,
  total_clients: 89,
  active_hostings: 64,
  pending_domains: 12,
  pending_payments: 8,
  monthly_growth: 18.5,
};

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Tech Solutions LLC",
    email: "contact@techsolutions.com",
    phone: "+1 (555) 000-0001",
    company: "Tech Solutions LLC",
    created_at: "2024-01-15",
    total_orders: 12,
    total_spent: 8500,
  },
  {
    id: "2",
    name: "Maria Fernanda Costa",
    email: "maria@mariafernanda.com",
    phone: "+1 (555) 000-0002",
    company: "Studio MF",
    created_at: "2024-02-20",
    total_orders: 5,
    total_spent: 3200,
  },
  {
    id: "3",
    name: "Good Taste Restaurant",
    email: "admin@goodtaste.com",
    phone: "+1 (555) 000-0003",
    company: "Good Taste Restaurant",
    created_at: "2024-03-10",
    total_orders: 8,
    total_spent: 5600,
  },
  {
    id: "4",
    name: "Dr. Robert Alves",
    email: "robert@clinicalves.com",
    phone: "+1 (555) 000-0004",
    company: "Alves Clinic",
    created_at: "2024-04-05",
    total_orders: 3,
    total_spent: 2100,
  },
  {
    id: "5",
    name: "Fashion Store Inc",
    email: "store@fashionstore.com",
    phone: "+1 (555) 000-0005",
    company: "Fashion Store Inc",
    created_at: "2024-04-18",
    total_orders: 15,
    total_spent: 11200,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    client_id: "1",
    client_name: "Tech Solutions LLC",
    description: "Institutional website development",
    value: 3500,
    status: "concluido",
    module: "sales",
    created_at: "2025-05-01",
    due_date: "2025-05-15",
  },
  {
    id: "ORD-002",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    description: "Online store creation",
    value: 2800,
    status: "processando",
    module: "sales",
    created_at: "2025-05-10",
    due_date: "2025-06-01",
  },
  {
    id: "ORD-003",
    client_id: "3",
    client_name: "Good Taste Restaurant",
    description: "Website with digital menu",
    value: 1900,
    status: "pendente",
    module: "sales",
    created_at: "2025-05-18",
    due_date: "2025-06-10",
  },
  {
    id: "ORD-004",
    client_id: "4",
    client_name: "Dr. Robert Alves",
    description: "Medical landing page",
    value: 1200,
    status: "concluido",
    module: "sales",
    created_at: "2025-04-20",
    due_date: "2025-05-05",
  },
  {
    id: "ORD-005",
    client_id: "5",
    client_name: "Fashion Store Inc",
    description: "Full e-commerce",
    value: 5800,
    status: "processando",
    module: "sales",
    created_at: "2025-05-22",
    due_date: "2025-07-01",
  },
];

export const mockWebsiteOrders: Order[] = [
  {
    id: "WEB-001",
    client_id: "1",
    client_name: "Tech Solutions LLC",
    description: "Monthly maintenance - Pro Plan",
    value: 350,
    status: "concluido",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
  {
    id: "WEB-002",
    client_id: "3",
    client_name: "Good Taste Restaurant",
    description: "Monthly maintenance - Basic Plan",
    value: 150,
    status: "pendente",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
  {
    id: "WEB-003",
    client_id: "5",
    client_name: "Fashion Store Inc",
    description: "Monthly maintenance - Enterprise Plan",
    value: 800,
    status: "concluido",
    module: "website_mensal",
    created_at: "2025-05-01",
    due_date: "2025-05-31",
  },
];

export const mockDomains: Domain[] = [
  {
    id: "DOM-001",
    domain: "techsolutions.com",
    client_id: "1",
    client_name: "Tech Solutions LLC",
    expiry_date: "2026-01-15",
    status: "ativo",
    auto_renew: true,
    registrar: "GoDaddy",
    price_yearly: 45,
  },
  {
    id: "DOM-002",
    domain: "mariafernanda.com",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    expiry_date: "2025-07-20",
    status: "ativo",
    auto_renew: false,
    registrar: "GoDaddy",
    price_yearly: 60,
  },
  {
    id: "DOM-003",
    domain: "goodtaste.com",
    client_id: "3",
    client_name: "Good Taste Restaurant",
    expiry_date: "2025-06-10",
    status: "pendente",
    auto_renew: true,
    registrar: "Namecheap",
    price_yearly: 45,
  },
  {
    id: "DOM-004",
    domain: "clinicalves.com",
    client_id: "4",
    client_name: "Dr. Robert Alves",
    expiry_date: "2025-05-30",
    status: "vencido",
    auto_renew: false,
    registrar: "Namecheap",
    price_yearly: 55,
  },
];

export const mockHostings: Hosting[] = [
  {
    id: "HOST-001",
    plan: "Pro Plan",
    client_id: "1",
    client_name: "Tech Solutions LLC",
    monthly_value: 120,
    expiry_date: "2025-12-15",
    status: "ativo",
    server: "US-SERVER-01",
    disk_usage: 4200,
    disk_limit: 10240,
  },
  {
    id: "HOST-002",
    plan: "Basic Plan",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    monthly_value: 45,
    expiry_date: "2025-08-20",
    status: "ativo",
    server: "US-SERVER-02",
    disk_usage: 1500,
    disk_limit: 5120,
  },
  {
    id: "HOST-003",
    plan: "Enterprise Plan",
    client_id: "5",
    client_name: "Fashion Store Inc",
    monthly_value: 280,
    expiry_date: "2025-11-18",
    status: "ativo",
    server: "US-SERVER-01",
    disk_usage: 18000,
    disk_limit: 51200,
  },
  {
    id: "HOST-004",
    plan: "Basic Plan",
    client_id: "3",
    client_name: "Good Taste Restaurant",
    monthly_value: 45,
    expiry_date: "2025-06-10",
    status: "suspenso",
    server: "US-SERVER-02",
    disk_usage: 800,
    disk_limit: 5120,
  },
];

export const mockUsers: User[] = [
  {
    id: "USR-001",
    name: "Douglas Admin",
    email: "admin@agencia.com",
    role: "admin",
    created_at: "2024-01-01",
    active: true,
  },
  {
    id: "USR-002",
    name: "Ana Finance",
    email: "financeiro@agencia.com",
    role: "financeiro",
    created_at: "2024-02-15",
    active: true,
  },
  {
    id: "USR-003",
    name: "Carlos Support",
    email: "suporte@agencia.com",
    role: "suporte",
    created_at: "2024-03-01",
    active: true,
  },
  {
    id: "USR-004",
    name: "Julia Sales",
    email: "vendedor@agencia.com",
    role: "vendedor",
    created_at: "2024-04-10",
    active: false,
  },
];

export const mockGeneratedSites: GeneratedSite[] = [
  {
    id: "SITE-001",
    client_id: "1",
    client_name: "Tech Solutions LLC",
    site_name: "Tech Solutions",
    business_type: "Technology",
    domain: "techsolutions.com",
    status: "publicado",
    created_at: "2025-01-15",
    url: "https://techsolutions.com",
  },
  {
    id: "SITE-002",
    client_id: "3",
    client_name: "Good Taste Restaurant",
    site_name: "Good Taste",
    business_type: "Restaurant",
    domain: "goodtaste.com",
    status: "em_producao",
    created_at: "2025-03-10",
  },
  {
    id: "SITE-003",
    client_id: "2",
    client_name: "Maria Fernanda Costa",
    site_name: "Studio MF",
    business_type: "Photography",
    domain: "mariafernanda.com",
    status: "publicado",
    created_at: "2025-02-20",
    url: "https://mariafernanda.com",
  },
];

export const mockMessages: WhatsAppMessage[] = [
  {
    id: "MSG-001",
    contact: "Tech Solutions",
    phone: "+15550000001",
    message: "Hi! I'd like to know about my domain expiration.",
    direction: "inbound",
    timestamp: "2025-05-26T10:30:00",
    status: "read",
    type: "text",
  },
  {
    id: "MSG-002",
    contact: "Tech Solutions",
    phone: "+15550000001",
    message: "Your domain techsolutions.com expires on 01/15/2026. Would you like to renew?",
    direction: "outbound",
    timestamp: "2025-05-26T10:32:00",
    status: "read",
    type: "template",
  },
  {
    id: "MSG-003",
    contact: "Good Taste Restaurant",
    phone: "+15550000003",
    message: "REMINDER: Your hosting expires on 06/10/2025. Renew now!",
    direction: "outbound",
    timestamp: "2025-05-25T09:00:00",
    status: "delivered",
    type: "billing",
  },
  {
    id: "MSG-004",
    contact: "Maria Fernanda",
    phone: "+15550000002",
    message: "Hi, the site looks great! Thank you so much for the work.",
    direction: "inbound",
    timestamp: "2025-05-24T16:45:00",
    status: "read",
    type: "text",
  },
];

export const mockAgents: AIAgent[] = [
  {
    id: "AGENT-001",
    name: "Initial Support",
    prompt:
      "You are an agency assistant. Answer questions about services, pricing and deadlines in a professional and friendly way.",
    active: true,
    triggers: ["hello", "hi", "good morning", "good afternoon", "want to hire"],
    responses: 342,
    created_at: "2024-01-15",
  },
  {
    id: "AGENT-002",
    name: "Automatic Billing",
    prompt:
      "Send automatic billing reminders to clients with pending payments. Be polite but firm.",
    active: true,
    triggers: ["upcoming due date", "pending payment"],
    responses: 87,
    created_at: "2024-02-01",
  },
  {
    id: "AGENT-003",
    name: "Technical Support",
    prompt:
      "Help clients with basic technical issues. For complex problems, escalate to the human support team.",
    active: false,
    triggers: ["problem", "error", "not working", "site down"],
    responses: 156,
    created_at: "2024-03-10",
  },
];
